;;; ------------------------------------------
;;; Do not edit this file. It was tangled from
;;; an org file.
;;; ------------------------------------------

(setq user-full-name "lengyuyang"
      user-mail-address "maoxiaoweihl@gmail.com")
